export const blogData = [
    {
      title: "Lorem ipsum dolor sit amet",
      subtitle:  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam et sapien vel lacus mollis sodales",
      img: "https://placehold.jp/150x150.png",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      button: "HELLO",
    },
    {
        title: "Lorem ipsum dolor sit amet",
        subtitle:  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam et sapien vel lacus mollis sodales",
        img: "https://placehold.jp/150x150.png",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        button: "HELLO",
      },
      {
        title: "Lorem ipsum dolor sit amet",
        subtitle:  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam et sapien vel lacus mollis sodales",
        img: "https://placehold.jp/150x150.png",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        button: "HELLO",
      },
      {
        title: "Lorem ipsum dolor sit amet",
        subtitle:  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam et sapien vel lacus mollis sodales",
        img: "https://placehold.jp/150x150.png",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        button: "HELLO",
      },
      {
        title: "Lorem ipsum dolor sit amet",
        subtitle:  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam et sapien vel lacus mollis sodales",
        img: "https://placehold.jp/150x150.png",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        button: "HELLO",
      },
      {
        title: "Lorem ipsum dolor sit amet",
        subtitle:  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam et sapien vel lacus mollis sodales",
        img: "https://placehold.jp/150x150.png",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        button: "HELLO",
      },
      {
        title: "Lorem ipsum dolor sit amet",
        subtitle:  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam et sapien vel lacus mollis sodales",
        img: "https://placehold.jp/150x150.png",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        button: "HELLO",
      },
      {
        title: "Lorem ipsum dolor sit amet",
        subtitle:  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam et sapien vel lacus mollis sodales",
        img: "https://placehold.jp/150x150.png",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        button: "HELLO",
      },
      {
        title: "Lorem ipsum dolor sit amet",
        subtitle:  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam et sapien vel lacus mollis sodales",
        img: "https://placehold.jp/150x150.png",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        button: "HELLO",
      },
]